name = "eddp"

[install]
completion = true
quiet = false
optimize = 2

#[sysimg]
#excluded_packages = ["EDDPotentials", "EDDPotentialsCli"]

#[sysimg.precompile]
#execution_file = ["test/runtests.jl"]
